module EndEntity
  STATUS_NEW = 10
  STATUS_FAILED = 11
  STATUS_INITIALIZED = 20
  STATUS_INPROCESS = 30
  STATUS_GENERATED = 40
  STATUS_REVOKED = 50
  STATUS_HISTORICAL = 60
  STATUS_KEYRECOVERY = 70
  STATUS_WAITINGFORADDAPPROVAL = 80
end
