module RevokeStatus
  NOT_REVOKED = -1
  AACOMPROMISE = 10
  AFFILIATIONCHANGED = 3
  CACOMPROMISE = 2
  CERTIFICATEHOLD = 6
  CESSATIONOFOPERATION = 5
  KEYCOMPROMISE = 1
  PRIVILEGESWITHDRAWN = 9
  REMOVEFROMCRL = 8
  SUPERSEDED = 4
  UNSPECIFIED = 0
end
